name: adventofcode_2021
description: A simple command-line application.
version: 1.0.0

environment:
  sdk: '>=2.14.4 <3.0.0'

dependencies: 
  vector_math: ^2.1.1

dev_dependencies:
  lints: ^1.0.0
  

